import discord
from discord import app_commands
from discord.ext import commands
from math import radians, sin, cos, acos, atan2, degrees

# ----------------------------
# ✈️ Qatar Airways PTFS Flight Plan Bot (Working)
# ----------------------------

# --- Bot setup ---
intents = discord.Intents.default()
bot = commands.Bot(command_prefix="!", intents=intents)

# --- PTFS Airport Database ---
airports = {
    "IZOL": {"name": "Izolirani International", "lat": -8.067, "lon": 115.177},
    "IRFD": {"name": "Greater Rockford", "lat": 40.651, "lon": -89.684},
    "ISAU": {"name": "Sauthemptona Airport", "lat": 50.950, "lon": -1.356},
    "IGRV": {"name": "Grindavik Airfield", "lat": 63.844, "lon": -22.430},
    "ITKO": {"name": "Tokyo International", "lat": 35.549, "lon": 139.779},
    "IPPH": {"name": "Perth International", "lat": -31.940, "lon": 115.967},
    "ILKA": {"name": "Larnaca Airport", "lat": 34.875, "lon": 33.624},
}

# --- Calculate distance ---
def calc_distance(dep, arr):
    return 6371 * acos(
        sin(radians(dep["lat"])) * sin(radians(arr["lat"])) +
        cos(radians(dep["lat"])) * cos(radians(arr["lat"])) *
        cos(radians(arr["lon"]) - radians(dep["lon"]))
    )

# --- Calculate initial heading ---
def calc_heading(dep, arr):
    lat1, lon1 = radians(dep["lat"]), radians(dep["lon"])
    lat2, lon2 = radians(arr["lat"]), radians(arr["lon"])
    dlon = lon2 - lon1
    x = sin(dlon) * cos(lat2)
    y = cos(lat1) * sin(lat2) - sin(lat1) * cos(lat2) * cos(dlon)
    brng = atan2(x, y)
    return (degrees(brng) + 360) % 360

# --- Generate waypoints ---
def generate_waypoints(dep, arr):
    return [
        {"name": "DEP", "desc": dep["name"]},
        {"name": "CRZ1", "desc": "Cruise waypoint 1"},
        {"name": "CRZ2", "desc": "Cruise waypoint 2"},
        {"name": "APP", "desc": f"Approach to {arr['name']}"},
        {"name": "ARR", "desc": arr["name"]},
    ]

# --- Bot ready event ---
@bot.event
async def on_ready():
    print(f"✅ Logged in as {bot.user}")
    try:
        synced = await bot.tree.sync()
        print(f"🔁 Synced {len(synced)} slash commands")
    except Exception as e:
        print(f"❌ Sync error: {e}")

# --- /flightplan command ---
@bot.tree.command(name="flightplan", description="Generate a realistic PTFS flight plan")
@app_commands.describe(departure="Departure airport code", arrival="Arrival airport code")
async def flightplan(interaction: discord.Interaction, departure: str, arrival: str):
    departure = departure.upper()
    arrival = arrival.upper()

    if departure not in airports or arrival not in airports:
        await interaction.response.send_message(
            "❌ Unknown airport code. Valid codes: IZ, GR, SA, GI, TK, PE, LA",
            ephemeral=True
        )
        return

    dep = airports[departure]
    arr = airports[arrival]

    dist = calc_distance(dep, arr)
    heading = calc_heading(dep, arr)
    flight_time = dist / 850  # km/h cruise
    waypoints = generate_waypoints(dep, arr)

    # --- Embed message ---
    embed = discord.Embed(
        title=f"🛫 Flight Plan: {departure} → {arrival}",
        description=f"**{dep['name']}** → **{arr['name']}**",
        color=0x5C0D30
    )
    embed.add_field(name="Distance", value=f"{dist:,.1f} km", inline=True)
    embed.add_field(name="Heading", value=f"{heading:.0f}°", inline=True)
    embed.add_field(name="Est. Flight Time", value=f"{flight_time:.1f} hrs", inline=True)
    embed.add_field(name="Cruise Altitude", value="FL320 (32,000 ft)", inline=True)

    wp_text = "\n".join([f"• **{w['name']}** – {w['desc']}" for w in waypoints])
    embed.add_field(name="Waypoints", value=wp_text, inline=False)
    embed.set_footer(text="Generated by Qatar Airways PTFS Bot ✈️")

    await interaction.response.send_message(embed=embed)


bot.run("YOUR_BOT_TOKEN_HERE")

